name: Development

on:

  pull_request:

    branches:
      - master

jobs:
  
  build:
    name: NodeJs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
          
      - name: Deployment
        run: |
          echo "Thank you for contributing"